### ISSUE TITLE
Fails to build with sdl2 0.9.1 

### ISSUE THREAD

**Issue by jonathandturner** [pcwalton/sprocketnes#19]
When trying to build with sdl2 0.9.1 and Rust 1.3, I get this error:

Compiling sprocketnes v0.1.0 (file:///Users/jonathan/Source/sprocketnes)
src/gfx.rs:7:12: 7:23 error: unresolved import `sdl2::InitBuilder`. There is no `InitBuilder` in `sdl2` [E0432]
src/gfx.rs:7 use sdl2::{InitBuilder, Sdl};
                        ^~~~~~~~~~~
src/gfx.rs:7:12: 7:23 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
Could not compile `sprocketnes`.

**Comment by jonas-schievink** [comment]
PR #18 should fix this

**Comment by petevine** [comment]
On Rust 1.7 nightly, i686 linux, the error's still there apparently:
````
Compiling sdl2 v0.12.1
   Compiling sprocketnes v0.1.0 (file:///home/petevine/sprocketnes-master)
src/gfx.rs:7:12: 7:23 error: unresolved import `sdl2::InitBuilder`. There is no `InitBuilder` in `sdl2` [E0432]
src/gfx.rs:7 use sdl2::{InitBuilder, Sdl};
````

**Comment by jonas-schievink** [comment]
@petevine That's what * dependencies do, unfortunately :(

PR #18 hasn't been merged yet, but it should at least fix the SDL problem

**Comment by petevine** [comment]
Oh sorry didn't check if it was still pending :)

**Comment by dbousamra** [comment]
This let me run sprocketnes for anyone who is running into overflow errors when running roms.
